name: Makefile CI

env:
  RUST_BACKTRACE: 1
  PROJECT_DIR: xks-axum
  ARTIFACT: aws-kms-xks-proxy

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check format
        run: cargo fmt --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml --all -- --check

  test-n-clippy:
    name: Unit Test and Clippy
    runs-on: ubuntu-22.04
    needs: style

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Stable
      uses: dtolnay/rust-toolchain@stable

    - name: Unit Test
      run: cargo test --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml

    - name: Clippy
      run: cargo clippy --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml

  miri:
    name: Check for Undefined Behavior
    runs-on: ubuntu-22.04
    needs: style

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri

    - name: Miri Test
      env:
        MIRIFLAGS: -Zmiri-disable-isolation
      run: cargo +nightly miri test --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml

  check-on-macos:
    name: Check on Mac
    runs-on: macos-latest
    needs:
      - style

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Check
      run: cargo check --manifest-path=${{ env.PROJECT_DIR }}/Cargo.toml

  # The pkcs11 crate v0.5.0 doesn't compile on Windows
  # https://docs.rs/pkcs11/latest/pkcs11/
  # check-on-windows:
  #   runs-on: windows-latest

  build:
    name: Build Packages

    runs-on: ubuntu-22.04
    needs: [test-n-clippy, miri, check-on-macos]

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Stable
      uses: dtolnay/rust-toolchain@stable

    - name: Install other dependencies
      run: sudo apt-get install -y rpm alien

    - name: Build xks-proxy rpm and deb
      run: make

    - name: Upload rpm
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT }}.rpm
        path: /home/runner/rpmbuild/RPMS/x86_64/*.rpm

    - name: Upload deb
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT }}.deb
        path: ./*.deb
