name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y rpm rpmlint alien

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: Build xks-proxy rpm and deb
      run: make
